import { readdir, readFile } from 'fs/promises'
import { resolve } from 'pathe'

export type FormKitRuntime = 'react' | 'vue'

export interface FormKitDocsRoute {
  pageOrder: number
  pageSlug: string
  route: string
  sectionOrder: number
  sectionSlug: string
  sectionTitle: string
  title: string
}

const SECTION_TITLES: Record<string, string> = {
  'api-reference': 'API Reference',
  essentials: 'Essentials',
  'getting-started': 'Getting Started',
  guides: 'Guides',
  inputs: 'Inputs',
  plugins: 'Plugins',
}

export function formKitDocsUrl(
  route: string,
  runtime: FormKitRuntime
): string {
  return `https://formkit.com${route}.${runtime}.md`
}

export async function collectDocsRoutes(
  docsContentRoot: string
): Promise<Array<FormKitDocsRoute>> {
  const sections = await readdir(docsContentRoot, {
    withFileTypes: true,
  })
  const routes: Array<FormKitDocsRoute> = []

  for (const section of sections) {
    if (!section.isDirectory()) continue
    if (section.name.startsWith('.') || section.name.startsWith('_')) continue

    const [sectionOrder, sectionSlug] = splitOrderedName(section.name)
    if (!sectionSlug || !(sectionSlug in SECTION_TITLES)) continue

    const sectionPath = resolve(docsContentRoot, section.name)
    const pages = await readdir(sectionPath, { withFileTypes: true })

    for (const page of pages) {
      if (!page.isFile()) continue
      if (page.name.startsWith('.')) continue
      if (!page.name.endsWith('.md')) continue
      if (page.name === 'README.md') continue

      const [pageOrder, pageSlug] = splitOrderedName(page.name.replace(/\.md$/u, ''))
      if (!pageSlug) continue

      const pagePath = resolve(sectionPath, page.name)
      const title = (await readDocTitle(pagePath)) ?? humanizeSlug(pageSlug)

      routes.push({
        pageOrder,
        pageSlug,
        route: `/${sectionSlug}/${pageSlug}`,
        sectionOrder,
        sectionSlug,
        sectionTitle: SECTION_TITLES[sectionSlug],
        title,
      })
    }
  }

  return routes.sort((a, b) => {
    if (a.sectionOrder !== b.sectionOrder) {
      return a.sectionOrder - b.sectionOrder
    }

    if (a.pageOrder !== b.pageOrder) {
      return a.pageOrder - b.pageOrder
    }

    return a.route.localeCompare(b.route)
  })
}

export function buildDocsReferenceMarkdown(
  routes: Array<FormKitDocsRoute>
): string {
  const lines = [
    '<!-- Generated by packages/cli/scripts/generate-skill-docs-index.mjs -->',
    '# FormKit Docs URL Index',
    '',
    'Use `.react.md` for React or Astro-with-React projects.',
    'Use `.vue.md` for Vue or Nuxt projects.',
    '',
    'Each entry below lists both runtime-specific markdown URLs for the same documentation page.',
    '',
  ]

  let activeSection = ''

  for (const route of routes) {
    if (route.sectionTitle !== activeSection) {
      if (activeSection) lines.push('')
      activeSection = route.sectionTitle
      lines.push(`## ${route.sectionTitle}`, '')
    }

    lines.push(`- ${route.title}`)
    lines.push(`  - React: ${formKitDocsUrl(route.route, 'react')}`)
    lines.push(`  - Vue: ${formKitDocsUrl(route.route, 'vue')}`)
  }

  lines.push('')

  return lines.join('\n')
}

async function readDocTitle(filePath: string): Promise<string | null> {
  const file = await readFile(filePath, 'utf8')
  const frontmatter = file.match(/^---\n([\s\S]*?)\n---/u)
  if (!frontmatter) return null
  const title = frontmatter[1].match(/^title:\s*(.+)$/mu)
  return title ? title[1].trim().replace(/^['"]|['"]$/gu, '') : null
}

function splitOrderedName(name: string): [number, string] {
  const orderedMatch = name.match(/^(\d+)\.(.+)$/u)
  if (orderedMatch) {
    return [Number(orderedMatch[1]), orderedMatch[2]]
  }
  return [Number.MAX_SAFE_INTEGER, name]
}

function humanizeSlug(slug: string): string {
  return slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}
